language: go

go:
  - "1.16.x"

install:
  - go install ./cmd/reviewdog
  # Install linters.
  - cd linters
  - go get golang.org/x/lint/golint
  - cd -
  - npm install

script:
  - golint ./... | reviewdog -f=golint -name=golint-travis -reporter=github-pr-check
