language: go

go:
  - "1.16.x"

install:
  - mkdir -p ~/bin/ && export PATH="~/bin/:$PATH"
  - curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b ~/bin
  - go get -u golang.org/x/lint/golint
  - npm install --save-dev textlint textlint-rule-no-mix-dearu-desumasu

script:
  - >-
    npx textlint -f checkstyle  README.md >> .textlint.log |
    cat .textlint.log | /home/travis/bin/reviewdog -f=checkstyle -name="textlint" -reporter="github-pr-review"
