version: '3.4'

services:
  pet-project:
    container_name: pet-project-app
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
          - pet-project-app:latest
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    volumes:
      - ../petProject:/src
      - ./configs/:/root/configs/
      - ./templates/:/root/templates/
    env_file:
      - .env

  mongodb:
    image: mongo:4.4-bionic
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_DATABASE=petMongo
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=12345
    volumes:
      - ./.data/db:/data/db
    ports:
      - 27018:27017