name: linters
on: [pull_request]
jobs:
  golang-ci:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: GolangCI-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Default is github-pr-check
  staticcheck:
    name: runner / staticcheck
    runs-on: ubuntu-latest
    needs: golang-ci
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Staticcheck
        uses: reviewdog/action-staticcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: github-pr-review
          # Report all results.
          filter_mode: nofilter
          # Exit with 1 when it find at least one finding.
          fail_on_error: false
  go-suggestion:
    name: runner / suggester / gofmt
    runs-on: ubuntu-latest
    needs: staticcheck
    steps:
      - uses: actions/checkout@v2
      - run: gofmt -w -s .
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: gofmt
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    needs: go-suggestion
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: npm install eslint --save-dev
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review # Change reporter.
