name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - develop
  pull_request:
  
env:
  GOLANG_LINT_VERSION: "v1.31"
  
jobs:  
  linter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Env
      run: go mod download && go get generate
      
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2.5.2
      with:
          version: ${{ env.GOLANG_LINT_VERSION }}
          args: -D errcheck

  tests:
    runs-on: ubuntu-latest
    needs: linter
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3

      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Env
        run: go mod download

      - name: Test
        run: |
          go test --short -coverprofile=cover.out -v ./...
          go tool cover -func=cover.out
          
