name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - develop
  pull_request:
jobs:  
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          golangci_lint_flags: "--enable-all --exclude-use-default=false"

  tests:
    runs-on: ubuntu-latest
    needs: golangci-lint
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3

      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Env
        run: go mod download && go get github.com/alecthomas/template@v0.0.0-20190718012654-fb15b899a751

      - name: Test
        run: |
          go test --short -coverprofile=cover.out -v ./...
          go tool cover -func=cover.out
          
