name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - develop
  pull_request:
jobs:  
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.3
          
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Env
      run: go mod download github.com/cpuguy83/go-md2man/v2
      
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2.5.2

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3

      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Env
        run: go mod download

      - name: Test
        run: go test --short ./...
