name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - develop
  pull_request:
jobs:  
  linter:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.2
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Env
      run: |
          go mod download
          go generate
          go get github.com/cpuguy83/go-md2man/v2@v2.0.0
          go mod tidy
      
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2.5.2
      with:
          version: v1.29
          args: -D errcheck

  tests:
    runs-on: ubuntu-latest
    needs: linter
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3

      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Env
        run: go mod download && go get github.com/alecthomas/template@v0.0.0-20190718012654-fb15b899a751

      - name: Test
        run: |
          go test --short -coverprofile=cover.out -v ./...
          go tool cover -func=cover.out
          
