name: golangci-lint
on:
#  push:
#    tags:
#      - v*
#    branches:
#      - master
#      - main
#      - develop
  pull_request:
jobs:  
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.16.3'

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
#      - name: Lint
#        run: |
#          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.41.1
#
#          golangci-lint run

  tests:
    runs-on: ubuntu-latest
    needs: golangci-lint
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3

      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Env
        run: go mod download

      - name: Test
        run: |
          go test --short -coverprofile=cover.out -v ./...
          go tool cover -func=cover.out
          
