name: reviewdog
on: [pull_request]
jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      # ...
      - name: Install reviewdog
        # use: reviewdog/action-setup@v1
        run: |
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./bin/reviewdog -reporter=github-pr-check -runners=golint,govet
          # or
          ./bin/reviewdog -reporter=github-pr-review -runners=golint,govet
